import XCTest
#if SWIFT_PACKAGE
@testable import HatInRingCore
#elseif DIRECT_TEST
#else
@testable import HatInRing
#endif

final class HatInRingTests: XCTestCase {
    func testStatusPrioritizesHardStops() {
        let status = RadarScoring.status(for: [.declared, .barred])

        XCTAssertEqual(status.tier, 0)
        XCTAssertEqual(status.label, "Ineligible")
    }

    func testMomentumUsesTopDeclarativePlusActivityAndRecency() {
        let candidate = makeCandidate(
            id: "newsom",
            keys: [.consideringQuote, .earlyState, .donors, .staffing, .mediaBlitz],
            lastSignal: "2026-06-12"
        )

        XCTAssertEqual(RadarScoring.momentum(for: candidate), 60)
    }

    func testFieldFiltersMoversAndInRing() {
        let declared = makeCandidate(id: "declared", keys: [.declared], lastSignal: "2026-05-26")
        let stale = makeCandidate(id: "stale", keys: [.mediaBlitz], lastSignal: "2026-01-01")
        let mover = makeCandidate(id: "mover", keys: [.softConsidering], lastSignal: "2026-06-10")
        let store = CandidateStore(candidates: [declared, stale, mover])

        XCTAssertEqual(Set(store.fieldCandidates(filter: .inRing).map(\.id)), ["declared"])
        XCTAssertEqual(Set(store.fieldCandidates(filter: .movers).map(\.id)), ["mover"])
    }

    func testWatchlistPersistsAfterTrackingTerminologyChange() {
        let suiteName = "HatInRingTests.\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suiteName)!
        defer { defaults.removePersistentDomain(forName: suiteName) }

        let first = HatInRingState(defaults: defaults)
        first.toggleWatch("newsom")
        first.toggleWatch("vance")

        let second = HatInRingState(defaults: defaults)

        XCTAssertTrue(second.isWatching("newsom"))
        XCTAssertTrue(second.isWatching("vance"))
        XCTAssertFalse(second.isWatching("harris"))
    }

    func testCurrentAndStalePipelineFreshnessCopyRetainsAsOfDate() {
        let freshness = DataFreshness(
            mode: .pipeline,
            asOf: "2026-07-06",
            sourceLabel: "Hat-in-Ring ingest pipeline",
            buildLabel: "Test"
        )
        let current = RadarScoring.dateFromISO("2026-07-09")!
        let stale = RadarScoring.dateFromISO("2026-07-10")!

        XCTAssertEqual(freshness.statusLabel(relativeTo: current), "UPDATED")
        XCTAssertEqual(freshness.statusLabel(relativeTo: stale), "STALE")
        XCTAssertTrue(freshness.summary.contains("July 6, 2026"))
        XCTAssertEqual(freshness.movementSubtitle(moverCount: 9), "9 moved in the latest pipeline run")
        XCTAssertEqual(freshness.wireSubtitle(dispatchCount: 40), "40 updated dispatches")
        XCTAssertEqual(freshness.recencyLabel(days: 1), "1d before update")
    }

    func testFreshnessMetadataConfiguresScoringDate() {
        let metadata = Data("""
        {
          "mode": "pipeline",
          "as_of": "2026-06-25",
          "source": "Hat-in-Ring ingest pipeline",
          "build": "Generated by test"
        }
        """.utf8)
        let candidateData = Data("[]".utf8)

        let store = CandidateStore.load(candidatesData: candidateData, freshnessData: metadata)

        XCTAssertEqual(store.freshness.statusLabel(relativeTo: RadarScoring.dateFromISO("2026-06-28")!), "UPDATED")
        XCTAssertEqual(store.freshness.snapshotDateText, "June 25, 2026")
        XCTAssertEqual(RadarScoring.asOfText, "June 25, 2026")
    }

    func testTabRecentCandidateAndReviewDecisionsPersist() {
        let suiteName = "HatInRingTests.\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suiteName)!
        defer { defaults.removePersistentDomain(forName: suiteName) }

        let first = HatInRingState(defaults: defaults, skipIntro: true)
        first.selectTab(.search)
        first.openCandidate("newsom")
        first.setReviewDecision(.confirm, for: "rid-a")
        first.setReviewDecision(.later, for: "rid-b")

        let second = HatInRingState(defaults: defaults, skipIntro: true)

        XCTAssertEqual(second.selectedTab, .search)
        XCTAssertEqual(second.recentCandidateID, "newsom")
        XCTAssertEqual(second.reviewDecision(for: "rid-a"), .confirm)
        XCTAssertEqual(second.reviewDecision(for: "rid-b"), .later)
        XCTAssertEqual(second.exportableReviewDecisions(), [ReviewDecision(rid: "rid-a", action: .confirm)])
    }

    func testBundledCandidatesJSONDecodesSuccessfully() {
        let store = CandidateStore.load()

        XCTAssertFalse(store.candidates.isEmpty)
        XCTAssertNil(store.criticalIssue)
        XCTAssertFalse(store.reviewItems.isEmpty)
    }

    func testCandidateMissingImageUsesEmptyPlaceholderPath() throws {
        let data = candidateJSON(extra: "")
        let candidate = try JSONDecoder().decode(Candidate.self, from: data)

        XCTAssertEqual(candidate.imagePath, "")
    }

    func testCandidateSourceURLDecodesAndValidates() throws {
        let data = candidateJSON(extra: ", \"sourceUrl\": \"https://example.com/report\"")
        let candidate = try JSONDecoder().decode(Candidate.self, from: data)

        XCTAssertEqual(candidate.sourceURL?.absoluteString, "https://example.com/report")
    }

    func testMissingCandidateDataCreatesCriticalIssue() {
        let store = CandidateStore.load(candidatesData: nil)

        XCTAssertTrue(store.candidates.isEmpty)
        XCTAssertEqual(store.criticalIssue?.title, "Candidate data unavailable")
    }

    func testMalformedCandidateDataCreatesCriticalIssue() {
        let store = CandidateStore.load(candidatesData: Data("not json".utf8))

        XCTAssertTrue(store.candidates.isEmpty)
        XCTAssertEqual(store.criticalIssue?.title, "Candidate data could not load")
    }

    private func makeCandidate(
        id: String,
        keys: [SignalKey],
        lastSignal: String,
        delta: Int = 0
    ) -> Candidate {
        Candidate(
            id: id,
            name: id.capitalized,
            party: "Democrat",
            role: "Governor",
            bucket: "considering",
            keys: keys,
            confidence: "High",
            delta: delta,
            lastSignal: lastSignal,
            headline: "Signal headline - Source",
            why: "Fixture",
            quote: "",
            tags: [],
            imagePath: "assets/candidates/newsom/01_governor_of_california_gavin_newsom_cropped_3x4_jp.jpg",
            pollLead: nil
        )
    }

    private func candidateJSON(extra: String) -> Data {
        Data("""
        {
          "id": "fixture", "name": "Fixture Person", "party": "Independent",
          "role": "Governor", "bucket": "considering", "keys": ["softConsidering"],
          "conf": "High", "delta": 1, "lastSignal": "2026-07-06",
          "headline": "Fixture headline - Source", "why": "Fixture reason",
          "quote": "", "tags": []\(extra)
        }
        """.utf8)
    }
}
