import XCTest
#if SWIFT_PACKAGE
@testable import HatInRingCore
#elseif DIRECT_TEST
#else
@testable import HatInRing
#endif

final class HatInRingTests: XCTestCase {
    func testStatusPrioritizesHardStops() {
        let status = RadarScoring.status(for: [.declared, .barred])

        XCTAssertEqual(status.tier, 0)
        XCTAssertEqual(status.label, "Ineligible")
    }

    func testMomentumUsesTopDeclarativePlusActivityAndRecency() {
        let candidate = makeCandidate(
            id: "newsom",
            keys: [.consideringQuote, .earlyState, .donors, .staffing, .mediaBlitz],
            lastSignal: "2026-06-12"
        )

        XCTAssertEqual(RadarScoring.momentum(for: candidate), 60)
    }

    func testFieldFiltersMoversAndInRing() {
        let declared = makeCandidate(id: "declared", keys: [.declared], lastSignal: "2026-05-26")
        let stale = makeCandidate(id: "stale", keys: [.mediaBlitz], lastSignal: "2026-01-01")
        let mover = makeCandidate(id: "mover", keys: [.softConsidering], lastSignal: "2026-06-10")
        let store = CandidateStore(candidates: [declared, stale, mover])

        XCTAssertEqual(Set(store.fieldCandidates(filter: .inRing).map(\.id)), ["declared"])
        XCTAssertEqual(Set(store.fieldCandidates(filter: .movers).map(\.id)), ["mover"])
    }

    func testWatchlistPersistsToUserDefaults() {
        let suiteName = "HatInRingTests.\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suiteName)!
        defer { defaults.removePersistentDomain(forName: suiteName) }

        let first = HatInRingState(defaults: defaults)
        first.toggleWatch("newsom")
        first.toggleWatch("vance")

        let second = HatInRingState(defaults: defaults)

        XCTAssertTrue(second.isWatching("newsom"))
        XCTAssertTrue(second.isWatching("vance"))
        XCTAssertFalse(second.isWatching("harris"))
    }

    func testFreshnessCopyComesFromPipelineUpdate() {
        let freshness = DataFreshness.bundled

        XCTAssertEqual(freshness.statusLabel, "UPDATED")
        XCTAssertEqual(freshness.movementSubtitle(moverCount: 9), "9 moved in the latest pipeline run")
        XCTAssertEqual(freshness.wireSubtitle(dispatchCount: 40), "40 updated dispatches")
        XCTAssertEqual(freshness.recencyLabel(days: 1), "1d before update")
    }

    func testFreshnessMetadataConfiguresScoringDate() {
        let metadata = Data("""
        {
          "mode": "pipeline",
          "as_of": "2026-06-25",
          "source": "Hat-in-Ring ingest pipeline",
          "build": "Generated by test"
        }
        """.utf8)
        let candidateData = Data("[]".utf8)

        let store = CandidateStore.load(candidatesData: candidateData, freshnessData: metadata)

        XCTAssertEqual(store.freshness.statusLabel, "UPDATED")
        XCTAssertEqual(store.freshness.snapshotDateText, "June 25, 2026")
        XCTAssertEqual(RadarScoring.asOfText, "June 25, 2026")
    }

    func testTabRecentCandidateAndReviewDecisionsPersist() {
        let suiteName = "HatInRingTests.\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suiteName)!
        defer { defaults.removePersistentDomain(forName: suiteName) }

        let first = HatInRingState(defaults: defaults, skipIntro: true)
        first.selectTab(.search)
        first.openCandidate("newsom")
        first.setReviewDecision(.confirm, for: "rid-a")
        first.setReviewDecision(.later, for: "rid-b")

        let second = HatInRingState(defaults: defaults, skipIntro: true)

        XCTAssertEqual(second.selectedTab, .search)
        XCTAssertEqual(second.recentCandidateID, "newsom")
        XCTAssertEqual(second.reviewDecision(for: "rid-a"), .confirm)
        XCTAssertEqual(second.reviewDecision(for: "rid-b"), .later)
        XCTAssertEqual(second.exportableReviewDecisions(), [ReviewDecision(rid: "rid-a", action: .confirm)])
    }

    func testReviewQueueLoadsFromBundleWhenAvailable() {
        let store = CandidateStore.load()

        XCTAssertFalse(store.candidates.isEmpty)
        XCTAssertFalse(store.reviewItems.isEmpty)
        XCTAssertNotNil(store.reviewItems.first { $0.rid == "5d0e43385abd" })
    }

    func testMissingCandidateDataCreatesCriticalIssue() {
        let store = CandidateStore.load(candidatesData: nil)

        XCTAssertTrue(store.candidates.isEmpty)
        XCTAssertEqual(store.criticalIssue?.title, "Candidate data unavailable")
    }

    func testMalformedCandidateDataCreatesCriticalIssue() {
        let store = CandidateStore.load(candidatesData: Data("not json".utf8))

        XCTAssertTrue(store.candidates.isEmpty)
        XCTAssertEqual(store.criticalIssue?.title, "Candidate data could not load")
    }

    private func makeCandidate(
        id: String,
        keys: [SignalKey],
        lastSignal: String,
        delta: Int = 0
    ) -> Candidate {
        Candidate(
            id: id,
            name: id.capitalized,
            party: "Democrat",
            role: "Governor",
            bucket: "considering",
            keys: keys,
            confidence: "High",
            delta: delta,
            lastSignal: lastSignal,
            headline: "Signal headline - Source",
            why: "Fixture",
            quote: "",
            tags: [],
            imagePath: "assets/candidates/newsom/01_governor_of_california_gavin_newsom_cropped_3x4_jp.jpg",
            pollLead: nil
        )
    }
}
